pingfed.go
pingfed handler updated to cater for swipe being disabled on a users device as requested by issue #19. FYI: @rowanu @ltrifonov 
if a user disables swipe via swipe settings in the pingone mobile application, then the user will be prompted to enter their otp passcode.
=> support disabled swipe for pingone

README.md, cmd/saml2aws/main.go, keycloak.go, saml2aws.go
Adding KeyCloak support to saml2aws. I haven't figured out MFA yet so that isn't in the provider at this stage.
=> Add KeyCloak provider

README.md
=> Update readme for Windows

README.md
=> Add appveyor build status badge

cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_darwin.go, input.go, input_test.go
* Fixed missing error case handler on password entry
* Fixed else which assumed a saved username/password was available
fixes #46
=> fix(Logging) Reduced output and removed debugging.

.appveyor/appveyor.yml, choco/VERIFICATION.txt, choco/saml2aws.nuspec, default.build.ps1
- updated chocolatey version to 1.8.3
- add `VERIFICATION.txt` so that chocolatey review can verify package
- add reference to `LICENSE.md` into chocolatey package
=> Update chocolatey version to 1.8.4

cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/cfg/cfg_test.go, pkg/provider/adfs/adfs.go, pkg/provider/adfs2/adfs2.go, pkg/provider/pingfed/pingfed.go
=> fix(Config) Make AWS URN used in SAML login configurable.

pkg/provider/okta/okta.go
I've added support for push MFA via Okta Verify app
https://developer.okta.com/docs/api/resources/authn.html#verify-push-factor
Note my first commit was to split MFA logic out of the Authenticate method as it was growing out of control.
=> feat(Okta) add support for Okta Verify (push MFA)

pkg/provider/adfs/adfs.go, pkg/provider/adfs2/adfs2.go, pkg/provider/http.go, pkg/provider/jumpcloud/jumpcloud.go, pkg/provider/keycloak/keycloak.go, pkg/provider/okta/okta.go, pkg/provider/pingfed/pingfed.go
=> fix(Providers) Updated all providers to use proxy from Environment

pkg/prompter/prompter.go
=> fix(Prompt) Removed extra \n which broke the output.

glide.lock, glide.yaml
=> fix(Glide) Add logrus correctly to glide and track releases

.appveyor/appveyor.yml, default.build.ps1
Fixed the version number issue on build from a github tag.
=> Fix appveyor builds from github tags.

helper/osxkeychain/osxkeychain_darwin.go, pkg/provider/adfs2/adfs2.go, pkg/provider/adfs2/example/loginpage.html, pkg/provider/adfs2/example/passcode.html, pkg/provider/adfs2/ntlm.go, pkg/provider/adfs2/rsa.go, pkg/provider/adfs2/rsa_test.go, pkg/provider/keycloak/keycloak.go, saml2aws.go
This is a pretty unique situation in that the entire authentication flow is different between the default behaviour of the IDP and when it is configured to use RSA MFA tokens.
=> Added support for RSA tokens with ADFS 2.x

cmd/saml2aws/commands/login.go, pkg/awsconfig/awsconfig.go
This can be a pain for new installations so I am going to also create the .aws folder.
fixes #134
=> fix(awsconfig) Create .aws directory if it doesn't exist.

Gopkg.lock, Gopkg.toml, pkg/provider/pingfed/example/mfapage.html, pkg/provider/pingfed/pingfed.go, pkg/provider/pingfed/pingfed_test.go
=> fix(PingFed) Resolved issue with Ping MFA changing page.

pkg/provider/okta/okta.go
=> Add support for Okta Totp Authentication

pkg/provider/pingone/pingone.go, saml2aws.go, saml2aws_test.go
It corresponds to the following case.
* Configure SAML setting of AWS to PingOne
* Link PingOne with PingFederate
* Using PingID
=> Support PingOne and PingID

.gitignore, cmd/saml2aws/commands/configure.go, input.go, pkg/prompter/prompter.go, pkg/prompter/survey.go, pkg/provider/adfs/adfs.go, pkg/provider/adfs2/rsa.go, pkg/provider/jumpcloud/jumpcloud.go, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go, pkg/provider/okta/okta.go, pkg/provider/pingfed/pingfed.go, pkg/provider/pingone/pingone.go
Working on providing alternative CLI interfaces.
=> refactor(Prompter) Simplify and decouple the prompter.

Gopkg.lock, Gopkg.toml, README.md, pkg/provider/googleapps/example/challenge-totp.html, pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go, pkg/provider/http.go, saml2aws.go, saml2aws_test.go
fixes #90
* This supports otp and SMS second factor authentication.
* Updated aws sdk and dependencies.
=> feat(GoogleApps) Added googleapps provider and tests.

README.md, pkg/provider/googleapps/README.md, pkg/provider/googleapps/example/challenge-prompt.html, pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
* Also added some docs / notes on google apps setup.
=> feat(Google Apps) Added support for mobile prompt 2fa.

pkg/provider/pingfed/example/loginpage.html, pkg/provider/pingfed/example/loginpage_absolute.html, pkg/provider/pingfed/pingfed.go, pkg/provider/pingfed/pingfed_test.go
fixes https://github.com/Versent/saml2aws/issues/186
=> account for absolute URLs in login pages

pkg/provider/googleapps/googleapps.go
Hi, @wolfeidau
The problem of #194 was caused by not being Japanese-ready.
Please merge.
=> Japanese correspondence of googleapps

pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
Fixes #197 
Would love to see this merged soon since I am having some issues publishing this binary locally. (not familiar with Go)
=> Add new message from google login

pkg/provider/pingfed/example/login2.html, pkg/provider/pingfed/pingfed.go, pkg/provider/pingfed/pingfed_test.go
Turns out our implementation of ping doesn't have the same form identifiers as others, to overcome this I have made the code use `pf.pass` to match the login form.
=> fix(Pingfed) Adjusted selectors to be more lenient.

pkg/provider/onelogin/onelogin.go
The focus of this PR is to fix a bug with OneLogin Protect. The current implementation in the API has a race condition and sometimes it sends multiple push notifications. The issue has been reported to OneLogin and has been fixed. https://onelogin.ideas.aha.io/ideas/IDEAS-I-1588
In order to avoid the issue, we have to add `do_not_notify: true` in subsequent (polling) requests. This is what happens between lines 306 and 311.
=> [OneLogin] Fix duplicate push notifications w/ OLP

.travis.yml, ci/before_script_linux.sh, cmd/saml2aws/commands/login_linux.go, helper/secretservice/secretservice_linux.c, helper/secretservice/secretservice_linux.go, helper/secretservice/secretservice_linux.h, helper/secretservice/secretservice_linux_test.go
https://specifications.freedesktop.org/secret-service/
=> feat(secretservice) Add linux secret service support.

pkg/provider/onelogin/onelogin.go
This PR fixes a bug when using TOTP (e.g. _Google Authenticator_), the app crashes without even prompting the user to enter a code. The bug resulted in the following message:
```
error authenticating to IdP: error verifying MFA: OTP token blank
```
=> [OneLogin] Fix TOTP MFA bug: OTP token blank

pkg/provider/okta/okta.go
Okta introduced an additional HTTP request in the auth process flow which was addressed in 399beb7. However, in the case that polling does not need to happen, this additional request was not being made.
=> Make additional Okta auth process call if did not poll

pkg/provider/jumpcloud/jumpcloud.go
Followed the guideline that @jefmsmit posted in #230 for what their changed flow will be.
I've tested this against our JumpCloud environment using Ubuntu 18.04, and it appears to work properly for us.
=>  Reworked for upcoming JumpCloud login flow change:  #230

pkg/provider/googleapps/googleapps.go
This PR fixed for me the issue in handling with Captcha #203 
The implementation is pretty naive but at least it unblock the use-case.
=> Captcha handling

README.md, doc/provider/jumpcloud/README.md
I thought that this might be helpful for some
=> Adding documentation for JumpCloud

cmd/saml2aws/main.go
Adds the `--profile` flag to the `configure` command. Closes [#251].
=> Added --profile option to the configure command

README.md, cmd/saml2aws/main.go, input.go, pkg/cfg/cfg.go, pkg/flags/flags.go, pkg/provider/f5apm/README.md, pkg/provider/f5apm/example/loginpage.html, pkg/provider/f5apm/example/mfapage.html, pkg/provider/f5apm/f5apm.go, pkg/provider/f5apm/f5apm_test.go, saml2aws.go, saml2aws_test.go
Support for F5's Access Policy Manager as an additional identity provider. 
* Automatic detection of MFA
* Automatic detection of MFA options (push, token)
=> feature: Add f5apm provider

pkg/provider/pingfed/pingfed.go
This PR allows pinged to continue to follow redirects for scenarios where we're hoping through various IDP providers. More or less a copy of the same functionality in the pingone provider with the addition of handling a SAMLRequest form which isn't from AWS (Keycloak uses this).
Tested:
* pingfed
* pingfed -> keycloak
* pingfed + mfa -> keycloak
=> Pingfed should only attempt role extract at the final AWS step

cmd/saml2aws/commands/configure.go, cmd/saml2aws/main.go, pkg/flags/flags.go
This is my attempt at solving #299
=> Passing in configFlag to NewConfigManager() instead of the const

Makefile, pkg/provider/pingone/example/selectdevice.html, pkg/provider/pingone/pingone.go, pkg/provider/pingone/pingone_test.go
Supported the case of registering multiple MFA devices.
=> Support Multi MFA Devices for PingOne Provider

cmd/saml2aws/main.go
to allow `saml2aws configure -a saml --idp-provider=Shibboleth`
=> Add Support for Shibboleth idp-provider in cli

pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
Implements #305
Workaround for #238, #311
=> Try alternate Google 2FA method if primary isn't supported

doc/provider/aad/README.md, pkg/provider/aad/aad.go, saml2aws.go
For the users who using `OneWaySMS` method.
=> Add `OneWaySMS` MethodType to AzureAD provider

aws_account.go
Hi, I've found that `saml2aws` is not working properly with aws china region.
So I've created PR for it.
Thank you,
=> support_china_region

cmd/saml2aws/main.go
Fixes: https://github.com/Versent/saml2aws/issues/373
=> Added Missing IDP Provider

README.md
* Added section for Linux installation in readme
=> (readme) Linux installation notes

pkg/provider/okta/okta.go
I tested this and it fixed https://github.com/Versent/saml2aws/issues/382 for me
Since the page for MFA in Okta desn't contain `form[action=\"https://signin.aws.amazon.com/saml\"]"` in `docIsFormRedirectToAWS`, the whole `if` block is skipped and we get the `Unknown document type` error.
This moves the MFA requesting code outside of that check so that it's hit if none of the other conditions are met.
=> Fix Okta MFA regression issue

cmd/saml2aws/main.go
Added Akamai provider for command line usage in idp-provider flag
=> Added Akamai for command line idp-provider

pkg/provider/aad/aad.go
fix  https://github.com/Versent/saml2aws/issues/351
=> fix aad `Response did not contain a valid SAML assertion`

README.md, cmd/saml2aws/main.go, pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
Uses token from --mfa-token flag instead of prompting if flag present.
=> Allow passing MFA token for GoogleApps

Dockerfile
Last commit comment referenced buildkite pipeline
=> Remove no longer in Dockerfile

pkg/provider/adfs/adfs.go
Adds support for AzureMfaServerAuthentication provider.
saml2aws 2.22.1:
```
Authenticating as %REDACTED% ...
error authenticating to IdP: unable to classify response from auth server
```
PR (user approves MFA request):
```
Authenticating as %REDACTED% ...
We've sent a notification to your mobile device.  Please respond to continue.
Selected role: %REDACTED%
Requesting AWS credentials using SAML assertion
Logged in as: %REDACTED%
```
PR (user denies MFA request):
```
Authenticating as %REDACTED% ...
We've sent a notification to your mobile device.  Please respond to continue.
error authenticating to IdP: Authentication denied.  Please try again.
```
=> Add support for AzureMfaServerAuthentication provider.

pkg/provider/aad/aad.go
=> FIX/AzureAD: Remove redundant WS call

pkg/provider/googleapps/u2f.go
Similar to https://github.com/Versent/saml2aws/pull/415
=> Removes call to open u2f device in googleapps

pkg/provider/googleapps/googleapps.go
I grabbed changes from @thecubed: 
- Google SKOTP and CAPTCHA: https://github.com/thecubed/saml2aws/commit/9781c437f393f5b3027094592ab22553e15ae81f
- If yubikey fails it asks for SKOTP
Second PR from https://github.com/Versent/saml2aws/pull/452
No tests failed
=> [googleapps] Adding fallback when yubikey fails, support for SKOTP and display CAPTCHA on iterm if available

cmd/saml2aws/commands/script.go
=> fix script's template for fish

pkg/provider/netiq/README.md, pkg/provider/netiq/netiq.go, pkg/provider/netiq/netiq_test.go, pkg/provider/netiq/responses/privileged_flow/idpLoginPass.html, saml2aws.go
Privileged authentication is skipping MFA whereas default authentation uses MFA, hence it's implemented as a MFA option
Privileged authentication uses a different login path than the default one.
=> add Privileged authentication option in NetIQ

cmd/saml2aws/commands/configure.go, cmd/saml2aws/commands/console.go, cmd/saml2aws/commands/exec.go, cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/script.go, cmd/saml2aws/main.go, go.mod, go.sum, input.go, pkg/provider/aad/aad.go, pkg/provider/adfs/adfs.go, pkg/provider/akamai/akamai.go, pkg/provider/googleapps/googleapps.go, pkg/provider/http.go, pkg/provider/okta/okta.go, pkg/provider/onelogin/onelogin.go, pkg/provider/shibboleth/shibboleth.go
* Removed spinner due to output issues
Fixes  #32
=> feat(logging) All logs to stderr on *nix and stdout on windows

README.md
just an update to the README.md to call out AzureAD integration and linked it to the existing doc on it.
=>  updated README.md for AzureAD doc

pkg/provider/adfs/adfs.go
Fixes #439 
I had the same problem with Symantec VIP, it was caused by change of html in Symantec dialog.
=> Modify case for handling mfa prompt.

pkg/provider/jumpcloud/jumpcloud.go
=> Fail if Jumpcloud 401 does not prompt for MFA

cmd/saml2aws/commands/list_roles.go
…eed to go to stdout
fixes https://github.com/Versent/saml2aws/issues/559
introduced by https://github.com/Versent/saml2aws/pull/502
/cc ppl involved in the original issue/PR and new issue
@wolfeidau  @LorisCazalon  @d3v1an7 @jghaines @MichaelMallett @valtaz
=> The roles from list-roles are output to stderr not stdout which is better for scripting

pkg/provider/pingone/pingone.go
When connected to a corporate VPN, login encounters a HTTP 401 response code and errors out because it is request authentication via SPNEGO. This fix allows the 401 to proceed and use the standard form authentication.
=> Allow 401 response and handle refresh for Pingone

.github/workflows/go.yml, .github/workflows/release.yml
=> chore(build): ensure builds of project are run in ci

pkg/provider/okta/okta.go
I believe this solves the issue reported in https://github.com/Versent/saml2aws/issues/507 by adding a Cookie Jar to the HTTP client and making a dummy request to the Okta App URL get a device token (`dt`) cookie from Okta.
It mirrors the approach from `aws-okta` - see https://github.com/segmentio/aws-okta/blob/master/lib/okta.go#L240
I could try to parse out the `dt` cookie (and any others - I think at least `sid` could be required) and thread them through manually, but it seems to me that keeping a Cookie Jar for this client is the right approach, since it's performing a multi-step interaction emulating a web browser.
This doesn't persist the Cookie Jar between runs like `aws-okta` does, so it doesn't directly address https://github.com/Versent/saml2aws/issues/492
=> Fix "Verify device" double prompt for Okta

README.md
https://github.com/Versent/saml2aws/issues/374
=> Add choco saml2aws link to README

README.md, go.mod, go.sum, pkg/provider/browser/browser.go, saml2aws.go, saml2aws_test.go
This provides a solution for #455 and enables users to trial and debug issues during the login process.
=> New browser based login using playright

cmd/saml2aws/main.go
Fix broken **Configuring IDP Accounts** link in [main.go](https://github.com/Versent/saml2aws/blob/master/cmd/saml2aws/main.go)
=> Fix broken Configuring IDP Accounts link

pkg/provider/googleapps/googleapps.go
Without this I get `error authenticating to IdP: page is missing saml assertion ` when trying to log in. I'm trying to trigger the otp code from google by using a Yubikey.
=> Google 2fa fix

pkg/provider/akamai/akamai.go, pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/u2f.go, pkg/provider/jumpcloud/jumpcloud_webauthn.go, pkg/provider/okta/okta.go, pkg/provider/okta/okta_webauthn.go, pkg/provider/onelogin/onelogin.go
https://github.com/Versent/saml2aws/issues/685
=> fix: remove fmt.Print* logging

pkg/provider/aad/aad.go
When conditional access is enabled, we will get the following response when requesting with `res, err = ac.client.Do(passwordLoginRequest)`.
```html
<html><head><title>Working...</title></head><body><form method="POST" name="hiddenform" action="https://login.microsoftonline.com:443/common/DeviceAuthTls/reprocess"><input type="hidden" name="ctx" value="***" /><input type="hidden" name="flowtoken" value="***" /><noscript><p>Script is disabled. Click Submit to continue.</p><input type="submit" value="Submit" /></noscript></form><script language="javascript">document.forms[0].submit();</script></body></html>
```
With [this change](https://github.com/Versent/saml2aws/pull/573), it no longer works as expected.
My changes are made to respect the changes and correct the relevant parts. …
=> [Azure AD]Fix Azure AD login with conditional access

pkg/provider/shibboleth/README.md, saml2aws.go
=> add ability do disable mfa for shibboleth provider (one string change)

.github/workflows/go.yml, pkg/cookiejar/jar.go
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Bump golangci-lint-action to v1.42.0

.github/workflows/go.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
https://github.com/Versent/saml2aws/issues/691
=> Add  macOS Big Sur 11 to GHA

pkg/provider/okta/okta.go
=> Allow double quotes around stateToken

.github/workflows/go.yml
correct https://github.com/Versent/saml2aws/actions/runs/4328583333/jobs/7558419657
=> Bump golangci-lint to v1.51.2

README.md
This MR replaces #243 due to it being 5 years old, and not having that branch anymore.
=> Update make instructions

go.mod, go.sum, pkg/provider/authentik/authentik.go, pkg/provider/authentik/authentik_test.go, pkg/provider/authentik/model.go, pkg/provider/authentik/model_test.go, saml2aws.go, saml2aws_test.go
[Authentik](https://goauthentik.io/) support, without MFA support, compatible with 2022.12.0(maybe old versions, not sure), up to 2022.12.2.
=> Add Authentik provider

pkg/provider/okta/okta.go
2 issues being addressed in here.
1. When multiple types of the same auth are found (e.g. multiple FIDO), it's not possible to identify which one to pick, given that in the prompt they are not possible to identify. See screenshot. 
This is fixed by adding the MFA name. See screenshot:
2. And most importantly, when the MFA options have the same name and the user is presented with a prompt, independently of the chosen option, the first one will always be the same picked. This is because the [survey code](https://github.com/Versent/saml2aws/blob/master/pkg/prompter/survey.go#L58-L62) will return the first index of any matched string (so 2 equal strings, and the same index is always returned, even if user picks 2nd). This is fixed by adding the auth name as pointed in the first point.
The …
=> Okta MFA - Present name of MFA. Prompt when multiple of same type are found

.github/workflows/go.yml
For reference - https://github.com/actions/runner-images/issues/6002
=> Bump ubuntu build env to latest

.dockerignore, .github/workflows/release.yml, .gitignore, .goreleaser.macos-latest.yml, .goreleaser.ubuntu-20.04.yml, Dockerfile, Dockerfile.build, Makefile
https://github.com/gliptak/saml2aws/actions/runs/5009684628
Docker image published
https://github.com/gliptak/saml2aws/pkgs/container/saml2aws
=> (copy) Add minimal Dockerfile and a goreleaser docker config

pkg/provider/keycloak/example/loginpage-another-way.html, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
Ignore other Keycloak login options. This will at least allow you to log in.
Relates to #1078
=> Ignore other login options

pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
=> GoogleApps: add a simple message so the user knows he must set-up 2 step verification

.github/workflows/go.yml
=> Bump upload-artifact/download-artifact actions to v4

README.md
Update README based on comments in [#748](https://github.com/Versent/saml2aws/issues/748)
=> docs(readme): add ubuntu install instruction [#748]

pkg/provider/browser/browser.go
This updates the `Browser` provider to load/save storageState so that on next login attempt the browser popup will use storageState data from previous login. This prevents having to retype and reselect all login options (username, password, mfa type, etc)  every time we get a saml2aws browser popup to login.
=> Reuse storageState between login attempts with `Browser` provider

.github/workflows/go.yml
=> Bump macos runner from 11 to 12

pkg/provider/keycloak/example/authError-invalidPassword-v2.html, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
support keycloak v2 in auth error validator
related to https://github.com/Versent/saml2aws/issues/948#issuecomment-2703840283
=> support invalid password for keycloak v2
