Versent/saml2aws

.gitignore, Makefile, README.md, aws_role.go, aws_role_test.go, cmd/saml2aws/commands/exec.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, config.go, input.go, pingfed.go, provider.go, saml.go, saml2aws.go, testdata/assertion_pingfed.xml
This includes:
* Better validation of aws roles, including catering for switched order.
* New command line option to override the default ADFS provider.
* Added a provider interface and options struct.
* Code tidy up and more validation.
* Added some build instructions to the `README.md`.
=> Add support for ping federation SAML provider

awsconfig.go
As already implemented with the env. variables this change will introduce some backwards compatibility especially with the Ansible dynamic inventory script.
=> save the token also as aws_security_token for legacy aws tools

README.md, adfs2.go, cmd/saml2aws/main.go, glide.lock, glide.yaml, saml2aws.go
My understanding is that ADFS 2.0 by default will fall back to HTTP Auth (NTLM/Basic), as opposed to the forms-based authentication used in later versions. That is at least the case on our 2008 R2 installations. [go-ntlmssp](https://github.com/Azure/go-ntlmssp) implements a `RoundTrip` decorator that respects the negotiation scheme used by ADFS 2.0, and implements NTLM authentication. See also: https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/.
I've implemented this as a separate "ADFS2" provider. I'm not sure how much sense it makes to merge it with the existing provider.
**TODO:**
=> ADFS 2.0 (HTTP Auth) support

Makefile, README.md, aws_account.go, aws_account_test.go, aws_role.go, cmd/saml2aws/commands/login.go, input.go, testdata/saml.html
This addresses #7 by POSTing to the interactive login form provided by AWS.  Account alias and role name is extracted from the markup.  The CLI prompt has been modified to group by account just like the login form.
I also setup `$ make install` to simplify installation.
=> Account aliases

README.md, cmd/saml2aws/main.go, jumpcloud.go, saml2aws.go
This adds JumpCloud support based on the existing PingFed provider.
The "hostname" is the IdP URL, e.g.: `sso.jumpcloud.com/saml2/some-application`
Considered omitting the `sso.jumpcloud.com/saml2/` and having the hostname property just be the application name. Could also add support for customizing the prompt on a per-provider basis in that case. Didn't want to do that without asking, but I'm happy to -- also happy to just leave as-is.
=> Add JumpCloud provider

README.md, cmd/saml2aws/main.go, okta.go, saml2aws.go
Adding Okta + Duo Mobile support to saml2aws. Initially only supporting push or passcode auth options for Duo, other options may come in the future. It's possible to add additional Okta mfa providers if and when required.
If mfa is required, user will be prompted to select either push or passcode. 
- push: a notification will be sent to the users registered mobile device. 
- passcode: user will be prompted to enter their otp from the Duo Mobile application.
It is assumed a user has already enrolled their mfa device. If not this will need to be done via a browser, it is not supported via the command line.
=> okta + duo idp support

.appveyor/appveyor.yml, choco/saml2aws.nuspec
Updating appveyor to `1.7.0`
Already built from my repo, will need to switch the appveyor build to this one soon.
=> Update appveyor build to 1.7.0

aws_account.go, aws_account_test.go, cmd/saml2aws/commands/exec.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_darwin.go, cmd/saml2aws/commands/login_test.go, cmd/saml2aws/main.go, config.go, helper/credentials/credentials.go, helper/credentials/saml.go, helper/osxkeychain/osxkeychain_darwin.c, helper/osxkeychain/osxkeychain_darwin.go, helper/osxkeychain/osxkeychain_darwin.h, helper/osxkeychain/osxkeychain_darwin_test.go, input.go
* Refactor all login related flags.
* Added role command line option
=> feat(storage) Keychain storage for password.

README.md, okta.go
This change adds support for additional two factor auth options for Okta: SMS and TOTP (Google Auth). I added the ability for user to select what two factor auth mechanism they want to use if there are multiple options enabled on the account. Looks like this:
```
Authenticating as user@email.com to Okta https://<otka url>
1) TOTP MFA authentication
2) SMS MFA authentication
3) DUO MFA authentication
Select which MFA option to use: 2
Enter verification code: 036882
Please choose the role you would like to assume:
...
```
=> Add additional two factor auth options (SMS and TOTP) to Okta provider

.appveyor/appveyor.yml, choco/saml2aws.nuspec, default.build.ps1
Appveyor will now build tags from Github and automatically use the version from the tag.
=> Add support for appveyor using Github release tags.

.appveyor/appveyor.yml
Sorry, last PR had a bug. I forgot to add the "only build on tags" flag to the appveyor.yaml
=> Fix: Only build appveyor on tags.

Makefile, cmd/saml2aws/main.go, saml2aws.go
- re-enable windows builds
- remove the default cli option for mfa=auto. If not specifying `--mfa=VIP` on the CLI, it would always default to `Auto` irrespective of what was in `.saml2aws` config
- put in some validation for provider/mfa combinations
Should resolve issue #114 and #115
=> fix_vip_mfa_win

cmd/saml2aws/main.go
I updated to latest version of saml2aws (v2.1.0) from v1 and was unable to use the exec subcommand. It is passing a blank string for profile, so I kept getting a security token is invalid error. 
```
InvalidClientTokenId: The security token included in the request is invalid.
status code: 403, request id: 90676c51-fd74-11e7-83f3-5d8ecdd37c03
error validating token
github.com/versent/saml2aws/cmd/saml2aws/commands.Exec
/Users/dan/golang/src/github.com/versent/saml2aws/cmd/saml2aws/commands/exec.go:40
main.main
/Users/dan/golang/src/github.com/versent/saml2aws/cmd/saml2aws/main.go:102
runtime.main
/usr/local/Cellar/go/1.9.1/libexec/src/runtime/proc.go:185
runtime.goexit
/usr/local/Cellar/go/1.9.1/libexec/src/runtime/asm_amd64.s:2337
```
=> Fix a copy and paste error preventing the exec command from passing in profile/password

cmd/saml2aws/commands/list.go, cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/main.go
This commit adds a command to list available role ARNs for the authenticated user.  This is helpful to allow the user to list their roles and then they can use the `--role` command line argument to automate exec calls without having to consult the AWS console.
=> Add list command to list role ARNs

cmd/saml2aws/commands/configure.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_test.go, cmd/saml2aws/main.go, helper/credentials/credentials.go, helper/credentials/saml.go, helper/osxkeychain/osxkeychain_darwin.go, helper/wincred/wincred_windows.go, pkg/flags/flags.go
This commit adds a password prompt to the `saml2aws configure` command.  This allows users to store their credentials during configure instead of having to store them the first time they run `login` or `exec`.  This seems to work better for my use case since `exec` calls will be automated and I don't want the user to be prompted at that time.
The user is also asked to confirm their password to ensure it is correct before storing while avoiding authentication.
The password flag has been moved into the common flags struct since it is now used by all commands.
=> Store password when using the configure command

Gopkg.lock, Gopkg.toml, README.md, cmd/saml2aws/commands/exec.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/awsconfig/awsconfig.go, pkg/awsconfig/awsconfig_test.go, pkg/cfg/cfg.go, pkg/cfg/cfg_test.go, pkg/dump/dump.go, pkg/flags/flags.go, pkg/provider/okta/okta.go, pkg/shell/env.go, pkg/shell/env_test.go, saml.go, saml_test.go, testdata/assertion.xml
see https://aws.amazon.com/blogs/security/enable-federated-api-access-to-your-aws-resources-for-up-to-12-hours-using-iam-roles/
* Refactor aws config to use structures
* Added saving of the expiry time for sessions and principal ARN
* Enable content dumping using env DUMP_CONTENT=true while debugging
=> feat(Login) Support sessions up to 12 hours :tada:

pkg/provider/http.go, pkg/provider/http_test.go, pkg/provider/okta/okta.go, pkg/provider/pingfed/pingfed.go
This feature adds an optional response validator which checks the status code is within the success and redirect ranges removing the need to validate every response with this logic explicity.
=> http(status) Add http status check to Ping and Okta providers.

cmd/saml2aws/commands/exec.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, input.go, pkg/cfg/cfg.go, pkg/cfg/cfg_test.go, pkg/flags/flags.go, pkg/flags/flags_test.go
So rather than only providing the option to override via a flag, this is now saved in the configuration :tada:.
=> feat(config) You can now configure an aws profile per account.

README.md, cmd/saml2aws/commands/exec.go, pkg/shell/env.go, pkg/shell/env_test.go
This was requested to enable running of scripts or tools which take an explicit aws profile name.
=> feat(exec) Added the profile ENV vars.

pkg/dump/dump.go, pkg/provider/adfs/adfs.go, pkg/provider/http.go, pkg/provider/keycloak/keycloak.go, pkg/provider/okta/okta.go, pkg/provider/pingfed/pingfed.go, pkg/provider/pingone/pingone.go
Based on feedback from users that the verbose was inconsistant across providers I added logging to the client where it should have been and removed all the shitty logging statements from all over the providers.
=> refactor(HTTP) Remove simplify request / response logging.

input.go
`saml2aws login` always displays role selection in random order, this can be a bit annoying, so added sort - always the same order.
let me know if it is ok, or we should be sorting on account number (or different field)
=> role selection prompt displays sorted list

pkg/dump/dump.go
The docs say (https://golang.org/pkg/net/http/httputil/#DumpRequestOut):
> DumpRequestOut is like DumpRequest but for outgoing client requests.
I don't actually see any difference in output when using `DUMP_CONTENT=true saml2aws login -a MY_PROVIDER --verbose`, but the docs seem pretty unambiguous that `DumpRequestOut` is the right API to use here, so I figure it's a safe change.
=> fix(pkg/dump) Use httputil.DumpRequestOut, per docs.

README.md, cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_test.go, cmd/saml2aws/main.go, pkg/creds/creds.go, pkg/flags/flags.go, pkg/provider/adfs/adfs.go, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
This flag allows easier automation for running saml2aws with
--skip-prompt. Only Keycloak and ADFS are currently supported.
---
In my exact use case, [saml2aws-auto](https://github.com/Rukenshia/saml2aws-auto), I currently have to rely on passing the MFA token by sending it through `stdin`. This does, however, not work reliably on Windows. I think this addition is quite useful for `--skip-prompt` use cases.
=> Add global mfa-token flag

README.md, pkg/provider/okta/README.md
Maybe this is unnecessary, but I spent a bit too much time stumbling around before I realized what URL `saml2aws` wants for Okta. The symptom when providing the base URL (e.g., `https://$YOUR_ORG.okta.com`) instead of the AWS application URL (e.g., `https://$YOUR_ORG.okta.com/home/amazon_aws/$OKTA_APP_ID/$SOME_OTHER_ID`) is that `saml2aws` fails with the error:
```
Response did not contain a valid SAML assertion
Please check your username and password is correct
```
Which is technically correct, but is not at all helpful for diagnosing that the username and password are not at all the problem.
In retrospect it is obvious, but a little note like this would have saved me some time.
=> Add Okta-specific notes.

Gopkg.lock, cmd/saml2aws/commands/configure.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, helper/credentials/saml.go, input.go, pkg/cfg/cfg.go, pkg/creds/creds.go, pkg/flags/flags.go, pkg/provider/onelogin/mock/provider.go, pkg/provider/onelogin/onelogin.go, pkg/provider/onelogin/onelogin_test.go, saml2aws.go, saml2aws_test.go
This PR adds OneLogin provider support. There are few things that would like to discuss. OneLogin is a bit different than other providers. In order to access their API, each application needs to have `app_id`, `client_id`, `client_secret`. Without these I cannot [generate access_token](https://developers.onelogin.com/api-docs/1/oauth20-tokens/generate-tokens-2), which is in turn used to [generate SAML](https://developers.onelogin.com/api-docs/1/saml-assertions/generate-saml-assertion) assertion and to [verify MFA](https://developers.onelogin.com/api-docs/1/saml-assertions/verify-factor) options.
This PR is very naive and adds the `app_id` into the common configuration and the when prompting for credentials I check if the provider is `OneLogin` and I validate if `client_id` and …
=> Add support for OneLogin

cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/awsconfig/awsconfig.go, pkg/flags/flags.go
fixes #227 
I currently use `aws-mfa` and I have a bash function that called switch.  It sets AWS_PROFILE and runs aws-mfa.  If my credentials are expired it will prompt me for my MFA.  If my credentials are still valid it moves along.
Currently with `saml2aws` I have no command I can run that says only reauthenticate me when my credentials have expired.
=> dont prompt for creds if they are currently valid

pkg/provider/okta/okta.go
I don't know anyone who uses Passcode anymore. Push should be the default.
If there's anyone who hates this change, we could make it a configuration item, but the code is not set up to do that right now.
=> Swapped the order to prefer Duo Push over Passcode.

Gopkg.lock, Gopkg.toml, cmd/saml2aws/main.go, pkg/provider/psu/README.md, pkg/provider/psu/psu.go, pkg/provider/psu/psu_test.go, saml2aws.go, saml2aws_test.go
I wanted to start a discussion around adding a somewhat custom provider to saml2aws. Penn State University has a somewhat customized implementation of Shibboleth+Cosign that prevents us from using the existing shibboleth provider.
I originally went down the road of building our own [tool](https://github.com/acobaugh/psu-saml-aws-login), then discovered saml2aws when researching methods of manipulating the user's AWS profile. This provider is effectively a straight import of the code from my own tool.
Notably, this provider:
* Uses https://github.com/headzoo/surf for web scraping. This is effectively a wrapper around goquery. I could change this to use goquery directly, but it would make the code more complicated
* Has some fmt.Print*'s to allow customizing the output format of some of the …
=> Add PSU provider

README.md, cmd/saml2aws/main.go
To support a direnv-style project where multiple IDPs or roles may need to be used, add `.Envar` to more flags. Also add the environment variables to help output and perform some minor housekeeping on the help output text.
This also updates the link in the help output, identified in #251 as being broken.
=> Add environment variable support to more flags

pkg/provider/pingfed/example/webauthn.html, pkg/provider/pingfed/pingfed.go, pkg/provider/pingfed/pingfed_test.go
=> Account for Ping WebAuthn detection

input.go
This changes the format from `role / account` to 'account / role', which
causes the subsequent sort to sort by account name and number.
Fixes #222 
This now gives a format as such:
```
Account: xxxxx-engineering (xxxxxxxxxx15) / administrator
Account: xxxxx-engineering (xxxxxxxxxx15) / systemadministrator
Account: xxx-enablers (xxxxxxxxxxx02) / administrator
Account: xxxxxxx-development (xxxxxxxxxx30) / administrator
Account: xxxxxxx-development (xxxxxxxxxx30) / kubernetes
Account: xxxxx-development (xxxxxxxxxx03) / administrator
Account: xxxxx-development (xxxxxxxxxx03) / databaseteam
```
which I think satisfies the original intent of #222
=> Change output format of AWS role selection

pkg/provider/pingone/pingone.go
The PingOne Provider I implemented is broken.
I reimplemented PingOne Provider based on PingFed Provider.
The difference from PingFed Provider is as follows.
* AuthnRequest can process.
* It can handle SAML Request not sent to AWS.
=> fix pingone

cmd/saml2aws/commands/login.go, pkg/cfg/cfg.go, pkg/cfg/cfg_test.go
This is a proposed fix for #109.
cfg.Validate() is used when necessary to check that the required fields
for a given account are present. LoadVerifyIDPAccount() is therefor
redundant.
- Use LoadIDPAccount() in the login command, to allow it to succeed even
if there are no configured IDP accounts.
- Completely remove LoadVerifyIDPAccount()
- Update tests as needed
Fixes #109
=> Allow login without configure

cmd/saml2aws/main.go
Add default http transport settings to honor tls verification and proxy settings. #274
=> Set default http transport settings

cmd/saml2aws/main.go
Allows `--skip-verify` to be configured with the an environment variable of `SAML2AWS_SKIP_VERIFY` to be consistent with other options.
=> Allow --skip-verify to be set via environment variable

cmd/saml2aws/commands/script.go
These changes are to address this issue: https://github.com/Versent/saml2aws/issues/267
* removed extra quote in setting secret key
* added single quotes around the values to treat as literal strings (shouldn't execute a profile name of `$(Remove-Item "C:\Windows" -Force)`)
=> add quotes remove extra equals from powershell env script

aws_role.go
While the [AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html) describes the Role attribute as a comma-delimited list, it does not explicitly forbid whitespace in delimiter. This is probably a configuration error on the ADFS side, however, the AWS console accepts assertions containing whitespace. That being the case, it does no harm to clean the ARN after scraping it.
=> Trim whitespace on extracted role ARNs

pkg/provider/jumpcloud/jumpcloud.go
The PR fixes the current behavior where the mfa prompt doesn't consider if a token is provided via the cli flag `--mfa-token` or `SAML2AWS_MFA_TOKEN` environment variable.
*Current behavior*
```shell
saml2aws login --mfa-token=$token # MFA Token prompt
```
*Expected behaviour*
```shell
saml2aws login --mfa-token=$token # no MFA Token prompt
```
=> Jumpcloud: check if mfa_token was passed via cli before prompting

pkg/provider/adfs/adfs.go
=> Passing AmazonWebservicesURN into QueryEscape to cater for URNs with spaces.

pkg/provider/adfs2/rsa.go
Adding a check for a SAML response after the first RSA code is submitted enables hard and virtual tokens which do not normally require nextCode. This should fix https://github.com/Versent/saml2aws/issues/248. The current tests do not include a page for nextCode so I cannot properly test that it does not break prior behavior.
=> Add check for SAML response after first RSA code submission

cmd/saml2aws/commands/login.go
An invalid SAML assertion sent to the AWS SAML signin page or any other
non-transport error (eg. 5xx status codes) would result in the prompter
in an infinite loop as it would be passed an empty list.
This just checks that we got at least 1 account back from AWS before
prompting the user.
=> login: check for empty AWS accounts in response

pkg/provider/adfs/adfs.go
Fixes #283
ADFS 5.0 on Windows Server 2019 introduces a hidden field with the name
of "UserName" and the id of "userNameInputOptionsHolder". saml2aws will
include this in the fields which it populates when submitting a request
to ADFS.
ADFS encounters an error when both "UserName" fields are populated, so
this change ensures that only "user" and "password" fields which are
visible to the user will be populated by saml2aws and submitted to ADFS.
=> Fix to Support ADFS5 Form Format

cmd/saml2aws/commands/script.go
`AWS_SESSION_TOKEM` -> `AWS_SESSION_TOKEN`
=> Fix fish env variable typo

README.md, cmd/saml2aws/commands/exec.go, go.mod, go.sum, pkg/shell/env.go, pkg/shell/env_test.go
The method created by @85matthew worked for a large majority of tools
but we found that some don't properly utilize the AWS_PROFILE env var.
In particular the Sops tool has issues.
This update makes it such that saml2aws behaves more like some other
tools in this space ([aws-vault](https://github.com/99designs/aws-vault) and [aws-okta](https://github.com/segmentio/aws-okta)). When the `--exec-profile`
flag is specified saml2aws now performs the role assumption via the STS
client from the AWS SDK. This means it will now do multiple levels of
role assumption _before_ executing the given command. Because saml2aws
is performing the assumption it no longer exports the AWS_PROFILE env
vars and the credentials that it export are fully fledged credentials
for the target profile.
BTW: @85matthew …
=> Update exec to perform role assumption from profile.

cmd/saml2aws/commands/configure.go, cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/flags/flags.go
Someone who uses [pass](https://www.passwordstore.org/) or other password managers to manage their credentials, storing credential into keychain can be an inconvenient option. This patch provides `--disable-keychain` option which disables behavior that storing credential into their local keychain.
=> Add disable-keychain option and implementation

pkg/creds/creds.go, pkg/provider/okta/README.md, pkg/provider/okta/okta.go, pkg/provider/okta/okta_test.go
I wasn't able to get `saml2aws` to work with Okta using MFA for our organization. We have the "Okta Verify" MFA (in reality just a TOTP scheme) configured for our AWS account and I was getting the "response does not contain a valid SAML assertion" error from https://github.com/Versent/saml2aws/issues/118.
According to [Okta support](https://support.okta.com/help/s/article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta) the "preferred solution" is gimme-aws-creds. I looked at [their code](https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/okta.py#L543-L548) and see they grabbed the state token from the page and resubmit to the `authn` endpoint.
Using that approach, I was able to get `saml2aws` to ask for my MFA code and return a valid AWS …
=> Fixes Okta MFA so that it works with TOTP

pkg/provider/shell/shell.go, saml2aws.go
Add new "external" provider that shells out to a separate script to retrieve the SAML response.
Uses the URL field as the command to pass to /bin/sh to execute.
Tested locally with an external script that hijacks the existing browser session to retrieve the SAML response, however could be used with anything really.
=> External provider

cmd/saml2aws/commands/exec.go
See Issue #378 
session-duration flag is not being passed through for exec action therefore sessions were receiving the default of 15 minutes (900 seconds). 
This will allow for valid values to be passed through.
If using credentials: (minimum- 900, maximum- 43200)
If using temporary credentials via role assumption: (minimum- 900, maximum- 3600) 
These are AWS limits and are not configurable from saml2aws.
=> Issue#378: Pass through session-duration flag for exec

cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, input.go
Every time I login using OneLogin as the Provider, I was asked the OneLogin Client ID and Client Secret, which was cumbersome.
So we changed it to allow passing API credentials from arguments or environment variables as well as the configure subcommand.
=> OneLogin API credential is received as an argument during login

pkg/provider/adfs/adfs.go, saml2aws.go
This implements both the prompt for a token as well as waiting for app confirmation (see #330). There is currently no way to actually chose the MFA type you expect, it'll just figure out what to use (mfa=Auto). There is also no timeout for waiting for app confirmation currently.
=> refactor ADFS provider to support AzureMFA as well

README.md, cmd/saml2aws/commands/console.go, cmd/saml2aws/main.go, go.mod, go.sum
As per https://segment.com/blog/secure-access-to-100-aws-accounts/ I have implemented AWS console login directly from saml2aws.
This will open using your default browser.
Note: Like the exec command, if your credentials are still active this will not prompt for login.
=> feat(console) Log into the AWS console from saml2aws

cmd/saml2aws/commands/console.go, cmd/saml2aws/main.go
The current logic wasn't covering all the expiration and unconfigured states, this is now fixed.
=> fix(console) Refactor token / config checks to login correctly

README.md, cmd/saml2aws/commands/script.go, pkg/shell/env.go, pkg/shell/env_test.go
This functionality allows for use cases such as creating custom
credential providers with botocore
=> Export AWS_CREDENTIAL_EXPIRATION with token expiration

pkg/provider/okta/okta_webauthn.go
This is causing an error - apparently the call to `Open` was always returning an error and we were never checking it until you added the comment that checked for it here https://github.com/Versent/saml2aws/commit/e602111db872da7dd308f7ead7e70b18974642e7
Tested without and confirmed the call was unnecessary.
=> Removes call to open FIDO device in Okta

cmd/saml2aws/commands/exec.go
After this commit (https://github.com/Versent/saml2aws/commit/2ace3880edd46109f6b425b06d384c9b22fee79d) the following error occurred only when using exec-profile
```
% saml2aws -a sample_idp exec --exec-profile=some-profile -- aws s3 ls
Credentials were refreshed, but the refreshed credentials are still expired.
exit status 255
```
I checked AWS_CREDENTIAL_EXPIRATION. Then, the zero value was set as follows.
```
% saml2aws -a sample_idp exec --exec-profile=some-profile -- bash -c "env | grep -i AWS_CREDENTIAL_EXPIRATION"
AWS_CREDENTIAL_EXPIRATION=0001-01-01T00:00:00Z
```
When modified like this branch, the following is modified and the command can be executed.
```
% ./saml2aws -a sample_idp exec --exec-profile=some-profile -- bash -c "env | grep -i AWS_CREDENTIAL_EXPIRATION" …
```
=> fix using exec-profile

.appveyor/appveyor.yml
master build throws glide error at https://ci.appveyor.com/project/davidobrien1985/saml2aws/branch/master
I'm not sure how Appveyor is triggered
=> Remove glide from Appveyor

pkg/provider/okta/okta.go
In line with `IdentifierDuoMfa`:
https://github.com/Versent/saml2aws/blob/e602111db872da7dd308f7ead7e70b18974642e7/pkg/provider/okta/okta.go#L562
I've stumbled upon a problem (#429) where Okta Push MFA getting an error after 8 successful calls to API, which is with current timeouts is 800ms. With this change in place, I'll still get an error after 8 successful calls, but it will give me 24 seconds to push "Yes, it's me" button on my phone in the Okta app instead of current ~1 second.
Details of the problem are in the linked issue.
=> Increase waiting sleep for Okta Push to 3 seconds

pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
Fixes #203, fixes #444
Google has been changing a number of their login pages recently. As a
result of that, their CAPTCHA page doesn't behave exactly as before, nor
do some of the login pages themselves.
This change is designed to be backwards compatible with the existing
Google login and captcha pages, as it appears that the changes are not
completely propogated through their systems at this time. This has made the change a bit verbose, but by necessity (this whole provider could probably use a refactor at some point).
This commit contains a fair number of changes, among which are:
- Support for generating absolute URLs from relative paths
- Some of the fields being references in `src` and `action`
attributes are now relative, so we need to expand them
- Support for logging into a final …
=> Add support for new Google Login Page Formats

input.go
This fixes the issue: Selecting the first role does not work #421
This worked up to version 2.21.0 but was broken after that when you hit enter after showing the roles. You would have to hit the down and then up arrow to select the first item.
It does seem strange that this worked up till 2.21.1 version as I couldn't find anything merged that changed this code besides maybe this one: https://github.com/Versent/saml2aws/pull/402
=> Set default to first item for role selection.

pkg/provider/googleapps/googleapps.go
Following #445 and [this issue in the pr](https://github.com/Versent/saml2aws/pull/445#issuecomment-593485448)
The login via GoogleApps was not working for me.
The Authentication page was consistently returning 400 instead
of the 302 Redirect that is followed by a 200 OK
Adding the `bgresponse` to the formData fixed it.
=> [provider][googleapps] - Add bgresponse=js_disabled

cmd/saml2aws/commands/list_roles.go
The "list-roles" command would always pass the assertion to AWS assuming it would receive the list of roles back and broke when there was only a single role to choose from, because AWS automatically redirects to the Console when there is only one role in the assertion.
=> Print roles immediately if only one role in SAML assertion

cmd/saml2aws/commands/script.go
same as https://github.com/Versent/saml2aws/issues/471 but for powershell
`saml2aws.exe script --shell=powershell`
// snip
`$env:AWS_CREDENTIAL_EXPIRATION='error generating template: template: envvar_script:6:35: executing "envvar_script" at <.Expires>: Expires has arguments but cannot be invoked as function`
=> fix script's template for powershell

README.md, aws_account.go, cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/awsconfig/awsconfig.go, pkg/cfg/cfg.go, pkg/flags/flags.go, saml.go
Additional work on top of #469 to support how Okta's SAML response is formatted.  Okta returns the `Audience` as `urn:amazon:webservices` which is not that useful.   So this updates to grab the `Destination` attribute of the root element of the SAML response.
=> Get the AWS destination from the Destination, not Audience

aws_account.go, pkg/provider/okta/okta.go
Fixes #475.
Added the known SAML signin pages for the AWS GovCloud (US) and AWS China into the okta provider, as well as into the SAML assertion parser.
Note this may not be good, idiomatic golang...  Sorry, my first attempt at doing something with it.
=> Fixes for okta + govcloud

cmd/saml2aws/commands/console.go, cmd/saml2aws/main.go, pkg/flags/flags.go
This change makes it possible to present a link to aws console instead of opening a browser. If you run saml2aws in a headless vm / docker container you cant open the browser. You can then copy the link and open your browser on your host machine.
This is useful, when you use an windows developer machine with a ubuntu headless vagrant box for edititing code but you have no browser in the vm.
=> Add console flag to present a link instead of opening browser directly

pkg/provider/okta/okta.go
Saml2aws compares the configured MFA factor (with --mfa or the MFA
configuration option) with the display name of the availabile factors.
For the Okta Verify TOTP factor, the display name is "Okta MFA
Authentication", but the allowed configuration option is "OKTA", and so
when you set --mfa=OKTA (or the equivalent in the configuration file),
it doesn't match, and you get a push notification from Okta Verify
instead.
This change just makes the prefix comparison case insensitive, so
setting `--mfa=OKTA` will match the "Okta MFA Authentication" option,
and you are prompted for a TOTP code from the Okta Verify app.
Alternative fixes could be changing the display name to 'OKTA MFA Authentication', or allowing 'Okta' to be the entry specified on the command line, but the latter is inconsistent …
=> Fix use of OKTA (Okta verify TOTP) as an MFA provider setting

pkg/provider/aad/aad.go
In the MFA of Azure AD, the KMSI page is always displayed. 
To solve the problem, we need to get the `authSubmitURL` by using the response body of the KMSI page. 
It seems that `saml2aws` expects the specification for the response body below: https://github.com/Versent/saml2aws/blob/8a75db809a21ce7d412b64d3b7e1db593a5d6db6/pkg/provider/aad/aad.go#L885-L895
https://github.com/Versent/saml2aws/blob/8a75db809a21ce7d412b64d3b7e1db593a5d6db6/pkg/provider/aad/aad.go#L897-L903
In fact, we get a HTML as the response body like:
<details><summary>an example response body of <code>loginPasswordResp.URLPost</code></summary>
```html
<!DOCTYPE html>
<html dir="ltr" class="" lang="en">
<head>
<title>Sign in to your account</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta …
```
=> [Azure AD] Revert #435 for #464 fix

cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go
I was surprised to discover that `--config` flag and `SAML2AWS_CONFIGFILE` env var was only respected by `configure` subcommand, so I fixed it by making the flag global.
Please let me know if I misunderstood or missed something.
Thanks!
=> Make `config` flag global

pkg/provider/adfs2/rsa.go, pkg/provider/adfs2/rsa_test.go
Fixes #340, adding support for SecurIDv2Authentication and improving form data extraction.
An additional POST call is needed to establish a context:
- https://github.com/torric1/AWSCLI-MFA-RSAv2/blob/master/ros_aws-cli-py3-adfs3-mfa-securID.txt#L128-L132
- https://gist.github.com/jgard/17262e0fc073c82bc7930db2f5603446#file-get-awstempcred-ps1-L25-L29
=> Support SecurIDv2 Authentication

pkg/provider/aad/aad.go
I have previously added processing for KSMI pages after MFA at https://github.com/Versent/saml2aws/pull/509.
However, we have received reports from some users at #530 that authentication using Azure AD does not work properly.
I found the following description at https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/keep-me-signed-in.
> The following diagram shows the user sign-in flow for a managed tenant and federated tenant and the new keep me signed in prompt. This flow contains smart Logic so that the Stay signed in? option won't be displayed if the machine learning system detects a high-risk sign-in or a sign-in from a shared device.
This means that if the device is not trusted, the KMSI page may not be displayed.
- Supports KMSI page display logic after MFA
---
FIX: …
=> [Azure AD] Fixes #530: Supports KMSI page display logic after MFA

pkg/provider/keycloak/example/redirect.html, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
This enables the Keycloak provider to login when the SAML login page
responds with an `401 Unauthorized` response.
Closes #541
=> Keycloak follow redirect on 401 response

pkg/flags/flags_test.go
See the IDP metadata descriptor here for the urn that is provided by AWS GovCloud: https://signin.amazonaws-us-gov.com/static/saml-metadata.xml
=> Updated the AWS URN to match actual govCloud URN

README.md
I noticed that the instructions for Windows runs the `saml2aws --version` to verify its installation. But this command was missing in the MacOS and Linux equivalent.
This is a simple update to the README 
- keeps the instruction consistent across OSes.
- it is a helpful CLI command to verify the installation steps ran correctly.
=> Docs Update - Keep the CLI installation steps consistent

cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/commands/login.go
related to:
resolves: #551
When errors occur with Authentication, the message below is displayed:
```
Response did not contain a valid SAML assertion
Please check your username and password is correct
To see the output follow the instructions in https://github.com/versent/saml2aws/v2#debugging-issues-with-idps
```
This URL, resulted in a 404 which should now be fixed
* `https://github.com/versent/saml2aws/v2#debugging-issues-with-idps` -> `https://github.com/versent/saml2aws#debugging-issues-with-idps`
Built the binary locally and the link now works :D
=> Updating broken URL for IDP Issues

pkg/provider/keycloak/example/assertion.html, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
This fixes https://github.com/Versent/saml2aws/issues/566
=> Fix keycloak login when SAML response page contains input fields without 'name' attribute

pkg/provider/adfs2/rsa.go
This change set  `ChallengeQuestionAnswer` with `passcode` value.
Our third party is giving us a solution that the passcode input name is `ChallengeQuestionAnswer`
=> ADFS adding ChallengeQuestionAnswer input name

cmd/saml2aws/commands/login.go
Only printing the output to use `--profile` if the profile being used is anything other than `default`
=> exclude default profile prompt

cmd/saml2aws/commands/login.go
makes the login process less verbose by default when credentials are current, but still keeps the message available if someone really wants it
=> send "credentials are not expired" to debug log

pkg/page/form.go
if a form doesn't have an "action" attribute, the processor
falls back to using the page's document.URL instead of failing
=> modify page processor to work with action-less forms

pkg/provider/pingfed/pingfed.go
in addition to recognizing `pf.username` and `pf.pass`, identifies `USER` and `PASSWORD` as alternatives in the
pingfed SAML login form
=> add support for `USER` and `PASSWORD` fields in pingfed provider

README.md
Congratulations! `saml2aws` has been added to [homebrew-core](https://github.com/Homebrew/homebrew-core). Therefore, it can be installed right away with `brew install saml2aws` without having to add a tap.
Do you also want me to add a `tap_migrations.json` file to your own tap that will automatically migrate all installations to `homebrew-core`? (see https://docs.brew.sh/Migrating-A-Formula-To-A-Tap)
=> Change macOS install instruction to install from homebrew-core

README.md
It seems that by skipping --profile flag in credential_process authentication, saml2aws will use [saml] profile in `~/.aws/credentials` to store the temp keys. 
This could lead to the situation where person was authenticated in account A, credentials hasn't expired yet -> they are not renewed -> account A details are used, even though we want to access account B.
=> readme: Added profile in credential process

README.md, cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/cfg/cfg_test.go, pkg/flags/flags.go, pkg/samlcache/samlcache.go, pkg/samlcache/samlcache_test.go
You can now cache the SAML assertion after authentication using the flag
`--cache-saml`. You can use the flag at `configure` time and it will be
set on subsequent `login` and `list-roles` calls.
The timeout for a SAML assertion is set to 5min as a constant, and the
code makes it relatively easy to make it configurable if needed, like
for example override this per provider.
Fixes #526
=> Adding SAML Assertion caching feature

pkg/provider/okta/okta.go
I have taken the code from #564 and refactored / adjusted it a little.
Okta allows you to attach multiple Fido devices to your account, but `saml2aws` will only attempt the use the first device in the list returned from Okta. This results in an authentication failure if the local device does not match, with no way to select another device. This PR iterates through each Fido device on the account looking for a match on the local system. 
This required a slight refactor to make requests to Okta's verification endpoints more reusable, but will make future refactoring easier.
=> dustinblackman okta multi fido

README.md, cmd/saml2aws/commands/script.go, cmd/saml2aws/commands/script_test.go, cmd/saml2aws/main.go
`script` is currently structured around shell compatible outputs only.
Some tools handle native env files, while looking similar they are
syntactically different.
Refactored the script code for testability.
Added some documentation.
=> Adding ENV as a script output

README.md, cmd/saml2aws/commands/list_roles.go, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/flags/flags.go
Extra fixing of #526, allows to override the SAML cache file location in lieu of the default one.
Will allow different IDPAccount configurations to share a single SAML cache file.
Added to the documentation.
Fixed a Marshalling inconsistency with IDPAccount where Name is stored with
a capital lettter.
=> Adding SAML cache file path option

cmd/saml2aws/commands/login.go
After the implementation of the samlcache in #634, the message
"Authenticating as ..." is printed systematically,
expected behaviour would be to print it only when `saml2aws` performs
the authentication.
=> Only log the auth message when actually auth'ing

README.md
Adds some documentation on how to configure autocomplete for bash and zsh.
Fixes #631.
=> Adding autocomplete documentation

pkg/provider/jumpcloud/jumpcloud.go, pkg/provider/jumpcloud/jumpcloud_webauthn.go, pkg/provider/jumpcloud/jumpcloud_webauthn_test.go, saml2aws.go
* Adds support of devices like Yubikey via [WebAuthn ](https://fidoalliance.org/fido2/fido2-web-authentication-webauthn/)
* Adds support of [Duo 2fa](https://duo.com/) authentication 
should address #390 
- Copied some code from Okta with modifications, works with Yubikey
- Inspired by https://github.com/Versent/saml2aws/pull/489 
- Tested all three (TOTP, Duo and Yubikey) seems to be working.
Menu looks like that 
And here is similar to Okta FIDO prompt to press flashing key.
Duo auth menu similar to Okta
=> Add Webauthn and Duo support for JumpCloud

pkg/provider/googleapps/googleapps.go
Fixes #600
Been using the code in my own locally edited version for a few weeks now i've attached some of the `--verbose` logs for review 
Tho simply what the /challenge/dp requires to pass is all verified on the google side and the required session information is stored in `responseForm` already when goquery scrapes it.
Small improvement could be to check that that the page has loaded and loop back over the MFA Challenge select until it has but this will fix the immediate issue.
```
DEBU[0006] name: TL value: AM3QAYbXHNqNLu0bwbOyDGvfBr6HOqcdUc-u6JTy2DhZkofa0JtEnUGJxmiNTeHw  provider=googleapps
DEBU[0006] name: gxf value: AFoagUXJf8oSXgMM5Q4QfV3IQkXOCB0ABQ:1616061055976  provider=googleapps
DEBU[0006] name: Email value: matthew.gialelis@email.com  provider=googleapps
DEBU[0006] loginURL: …
```
=> Issue 600: Add Missing challange/dp for google provider

pkg/provider/shibboleth/README.md, pkg/provider/shibboleth/shibboleth.go
Shibboleth IdP v4 introduced a CSRF token as part of the login flow. Using the Shibboleth provider against a v4 IdP with the CSRF token enabled results in an error (see #638).
This PR extracts the CSRF token and includes it in subsequent responses.
=> Support Shibboleth IdP v4 with CSRF tokens

README.md
Linux instructions now include call to grab the latest release. There quite a few out there having issues on Linux since they're just pulling an outdated release per instructions (2.27.1)
=> fix: linux instructions to grab latest release

pkg/provider/okta/okta.go
When multiple FIDO keys are configured in an account saml2aws doesn't try all of them and fails with `The provided key handle is not present on the device, or was created with a different application parameter` 
The bug seems to be an off by one issue. After this fix it works as intended.
I have only tested this in my MacOS.
This might be the cause for #622
=> fix off by one bug in selecting mfa factors

pkg/provider/aad/aad.go
Change "SAMLAssersion" to "SAMLAssertion" in Authenticate() function.
=> Fix typo in error message

cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_test.go
This was causing expiration times to be processed incorrectly.
Closes #646
=> Fix ISO-8601 format of expiration time in login.go

cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_test.go
Turns out the root cause was not what my changes addressed. My changes didn't break anything, but for the sake of clarity, I'm mostly reverting them. The only remaing changes
after this commit are to use a named format, rather than a confusing format string, and keeping the the correct order of arguments in the unit test.
This change correctly fixes #646.
=> Revert changes to time format in #651, use named format specifier

pkg/provider/googleapps/googleapps.go
Captcha prompts are being sent to stderr which is the default for `log.PrintLn`, use `fmt.PrintLn` instead so it's sent to stdout instead of stderr.
=> Dont send captcha to stderr

README.md, pkg/cfg/cfg.go, pkg/provider/okta/okta.go, pkg/provider/pingfed/pingfed.go, pkg/provider/pingone/pingone.go, pkg/provider/shibbolethecp/shibbolethecp.go, pkg/provider/shibbolethecp/shibbolethecp_test.go
Nothing about the SAML response provided by the identity providers is tied
to Amazon other than the redirect URL and the provider ID. The provider ID
can be overridden with the aws_urn config parameter, but for some providers
the redirect URL is hardcoded in order to detect a page containing the SAML
response. This patch adds a target_url configuration parameter to allow the
hardcoded values to be overridden, making it possible to use the providers
for non-AWS purposes.
=> Make providers compatible with non-AWS targets

README.md
This change better documents the [SAML2AWS_DISABLE_KEYCHAIN](https://github.com/Versent/saml2aws/blob/master/cmd/saml2aws/main.go#L83) env variable alternative to the `--disable-keychain` flag available. My editor also cleaned up some whitespace in the document that I have added as a separate commit.
=> Add SAML2AWS_DISABLE_KEYCHAIN env variable to documentation

README.md, cmd/saml2aws/main.go, pkg/provider/auth0/README.md, pkg/provider/auth0/auth0.go, pkg/provider/auth0/auth0_test.go, saml2aws.go, saml2aws_test.go
I make Auth0 provider (but I don't use MFA, so this provider doesn't support MFA.). 
Could you review this PR?
Following steps are what this code does.
1. Get `connection` (scraping)
* Scraping `client_id` and `connection` mapping file ( `https://cdn.auth0.com/client/<CLIENT_ID>.js` ).
* This `connection` is used next step.
2. Get session information (official API)
* Use [Accept Request](https://auth0.com/docs/api/authentication?http#accept-request) API
* This requires `connection` but Auth0 doesn't provide official API for getting connections.
* Get `state` and `CSRF` token.
3. Pretend to login from HTML form by username/password (scraping)
* Use `state` and `CSRF` token getting before step and pretend to login from HTML form by username/password from …
=> Add Auth0 provider (without MFA support)

README.md, cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_test.go, cmd/saml2aws/main.go, go.mod, go.sum, helper/credentials/saml.go, pkg/cfg/cfg.go, pkg/creds/creds.go, pkg/flags/flags.go, pkg/provider/okta/okta.go, pkg/provider/okta/okta_test.go
* This is to use Okta Sessions API by default when authenticating
* Okta session cookie is stored in keychain/credentials store
* Use of Okta sessions can be disabled via CLI flags/config entry
* Remembers MFA device by default so that users do not get prompted for MFA every time (as long as the session is valid)
* Defaults to the previous authentication method when sessions are disabled by user
Binaries built & tested on `go version go1.16.4 darwin/amd64`
Please see README for more information.
=> Use Okta Sessions API

cmd/saml2aws/main.go, pkg/cfg/cfg.go
Make Browser a valid option for `provider` and `idp-provider` flags
This change fixes the error that it is **not** possible to configure a **Browser** `idp-provider` based profile without prompt.
```
~ via ❄️  impure (shell) took 9s
❯ saml2aws configure -a test --idp-provider Browser -r eu-central-1 --url 'https://xxx' --role 'arn:aws:iam::xxxxxxxxxxxx:role/xxx/xxx' --skip-promptsaml2aws: error: enum value must be one of Akamai,AzureAD,ADFS,ADFS2,GoogleApps,Ping,JumpCloud,Okta,OneLogin,PSU,KeyCloak,F5APM,Shibboleth,ShibbolethECP,NetIQ,Auth0, got 'Browser', try --help
```
P.s I'm not 100% sure if the solution to bypass the  **MFA** check is okish :thinking: 
P.s.s Whan #693 is merged I'm going to rebase this branch :smile:
=> Make Browser a valid option for provider and idp-provider flags

pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
Closes #687 
Before this PR, when the user inputs wrong password, the raised error was
> `error authenticating to IdP: page is missing saml assertion`
After this PR, when the user inputs wrong password, the raised error is
> `error authenticating to IdP: Password error`
@wolfeidau please let me know if there's anything else needed to merge this PR
=> Feature/handle wrong password with GSuite

pkg/provider/aad/aad.go
Trying to close https://github.com/Versent/saml2aws/issues/628
I tested locally and works for me (user with conditional MFA) and a co-worker (user without conditional MFA)
The biggest changes are:
1. Extracted MFA logic into its own function called `processAuth`. 
2. Now we call `processAuth` twice, after each time mfa was skipped
=> [aad] Adding support for conditional MFA

pkg/provider/http.go, pkg/provider/pingfed/pingfed.go, pkg/provider/pingone/pingone.go
This is the same change as in PR #574 for PingOne, but applied to PingFed for the same reason involving corporate VPN and a 401 for SPNEGO authentication.
=> Allow 401/SPNEGO response and handle refresh for PingFed

pkg/provider/jumpcloud/jumpcloud.go, pkg/provider/jumpcloud/jumpcloud_protect.go, pkg/provider/jumpcloud/jumpcloud_protect_test.go, pkg/provider/jumpcloud/utils.go, saml2aws.go
JumpCloud have released a new app that they call [JumpCloud
Protect](https://jumpcloud.com/press/introducing-jumpcloud-protect-free-mobile-multi-factor-authentication).
It is a free alternative to DUO for JumpCoud users that provides "push"
second factor. It would be useful to add this in if possible (we are
planning to use it).
=> Add JumpCloud Protect (PUSH) MFA support

cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/flags/flags.go, pkg/prompter/pinentry.go, pkg/prompter/pinentry_test.go, pkg/prompter/prompter.go
This PR adds a new type of Prompter called `Pinentry`.
The current prompter is very convenient for many things, but it requires a TTY at all time. Which is mostly the case when you use it and require the prompter, like a first time login, or selecting a role in the list.
However, when using `saml2aws` with the credential process, it only works if there is no 2FA or if the 2FA is detached (typically, using an app like MSAUTH). For users having to type their TOTP, the TTY is required.
Unfortunately, the AWS SDK is making calling the credential process and doesn't allow STDIN, hindering the ability to automate the TOTP. There _is_ a `--mfa_token` option, but requires some additional wrapping behind it to get the TOTP in real time and doesn't account for when the credentials are already valid …
=> Adding Pinentry as a prompter

pkg/provider/jumpcloud/jumpcloud.go
Responding to https://github.com/Versent/saml2aws/issues/757
Response body will be closed in case of 401 by the time we attempt to
compare it with 200 in case if deny or time out. Not sure how it slipped
in, given I used existing code. Perhaps never worked or I made a silly
change somewhere, e.g. closing response body handler.
It works correctly now.
=> Fix nil dereference when JumpCloud DUO is denied or timed out

pkg/provider/googleapps/googleapps.go
When attempting to authenticate to AWS using GoogleApps SAML, some users are receiving the following error when running the command `saml2aws login`:
```
Error authenticating to IdP.: error loading first page: failed to build login form data: could not find any forms matching the provided IDs.
```
Error page seen when reviewing the response from Google:
Previous workaround was to [change the provider](https://github.com/Versent/saml2aws/issues/750#issuecomment-1098542566) from `GoogleApps` to `Browser`, but this fix should make this no longer necessary.
Changing the `bgresponse` from `js_disabled` to `js_enabled` has fixed this for myself and a user in my organization.
Looking at [resources documented in this repo](https://github.com/Versent/saml2aws/tree/master/pkg/provider/googleapps#pri …
=> Change `bgresponse` to `js_enabled`

README.md, cmd/saml2aws/commands/login_linux.go, helper/linuxkeyring/linuxkeyring_linux.go, pkg/cfg/cfg.go
Prior to this change, you were not able to set the keyring backend to
your preferred keyring. This mean it was up to `saml2aws` figure out what
the appropriate backend to use depending on the operating system, and a
priority list of backends that are supported.
After this change, you can use the environment variable
`SAML2AWS_KEYRING_BACKEND` to set it to whatever keyring backend you
want. However, this setting is only available for Linux operating
systems (unless this feature is required for other operating systems).
This hopefully allows headless systems such as WSL to set their backend
to a keyring that doesn't rely on X11 and DBus (such as pass).
This hopefully resolves the following issues:
- #563
- #582
- #561
=> feat(keyring): ✨ Add support to set diff backend

pkg/provider/googleapps/googleapps.go
`loadFirstPage` function sends `bgresponse: enabled` to form data before posting, but this also needs to be done during the challenge POST, or you'll receive the infamous "This browser does not support Javascript.." message.
Small note: I haven't touched `go` outside of this project, so I'm unsure if there's a better way to do this, but this worked for me.
=> Add `bgresponse: js_enabled` to challenge post too.

pkg/provider/keycloak/example/mfapage2authenticators.html, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
This change enables usage of more than one authenticators in KeyCloak.
It tries all the authenticators one-by-one until one of them succeeds.
Previously only the first Authenticator was respected.
Resolves #838
=> Add multiple authenticator support for Keycloak

.appveyor/appveyor.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/Versent/saml2aws/issues/820
Build is failing https://ci.appveyor.com/project/davidobrien1985/saml2aws/branch/master
I don't have a way to test this PR
https://www.appveyor.com/docs/windows-images-software/
https://www.appveyor.com/docs/lang/go/
=> Bump Golang to 1.18 for Appveyor

pkg/provider/keycloak/keycloak.go
This is side effect of https://github.com/Versent/saml2aws/pull/839.
If you use wrong id/pw, it will cause an infinite loop.
To prevent this, I add a validation logic for invalid password.
@wolfeidau please check this pr.
=> fix infinite loop for keycloak

README.md
This is only a documentation change to the README.md file about support for SigV4A.
By default, the credentials returned by `saml2aws` do not support SigV4A. In order to enable SigV4A support you must use a regional STS endpoint which can be controlled via the `AWS_STS_REGIONAL_ENDPOINTS` environment variable which is picked up by aws-sdk-go.
I ran into this problem while trying to access an S3 Multi-Region Access Point with credentials provided via `saml2aws`. Direct access to my S3 buckets behind the MRAP worked fine but trying to go through the MRAP would always result in an HTTP 500 error from AWS with no useful information.
AWS Support finally pointed me to the note at the bottom of [Signing AWS API requests](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html# …
=> README.md - Added note about SigV4A support

.appveyor/appveyor.yml
after merging #827, Appveyor still failed https://ci.appveyor.com/project/davidobrien1985/saml2aws/builds/44234589
looking into it further, it might be that Appveyor runs on older Windows image with no current Golang
https://www.appveyor.com/updates/
https://www.appveyor.com/docs/windows-images-software/#golang
https://www.appveyor.com/docs/build-environment/
I don't have a way to test this PR
#820
=> Use Visual Studio 2019 for Appveyor

pkg/provider/onelogin/onelogin.go
Off the back of #780 being merged (thanks again!) this should be the last quirk to shore up OneLogin support for quite some time.
This PR addresses a particular quirk that I recently came across around the value of the `callback_url` field returned by the `saml_assertion` endpoint.
For some tenants, such as our own, this resolves to `api.us.onelogin.com` as a host URL which always routes to a 52.x IP address regardless of your nearest region.
The APIs available at `api.us.onelogin.com` are the same as those available under your own tenant (ie; `blah.onelogin.com`) except for the fact that they always resolve to the same set of instances. Depending on your geographic location, this can cause a `400 Bad Request` to appear due to erroneous routing.
For the initial MFA device query, you'll …
=> Always use OneLogin host instead of trusting callback URL

cmd/saml2aws/commands/configure.go
It is confusing as hell to have saml2aws request 2 flags that do not exist.
=> fix: rename needed flags for Onelogin

pkg/provider/adfs/adfs.go
Based on usage it looks like p#instruction is populated via javascript after page load. The entropy number is not present in the p#instructions element.
https://docs.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match
=> Fix ADFS auth when using MFA with number matching

.github/workflows/go.yml, .github/workflows/release.yml, .goreleaser.yml, README.md
This PR enables U2F support on Linux amd64. It builds on the work done in, and supersedes, #592.
There are no code changes, just build configuration updates:
* Pass `-tags=hidraw` to `go build` on Linux amd64, which enables U2F as per [the documentation](https://github.com/marshallbrekka/go-u2fhost#linux) in the underlying U2F library.
* Install the `libudev-dev` package and use `CGO_ENABLED=1` on Linux, because U2F support uses libudev.
* Update the Github workflows to build the package correctly on Linux (untested).
* Update the build documentation in the README.
Closes: #419 
Closes: #592
Note that this changes the release builder from macos to ubuntu. I have no way of testing the resulting macos binary to see if it still works, so would appreciate if someone else could confirm this.
=> Support U2F on Linux

.github/workflows/go.yml, .github/workflows/release.yml, Makefile
https://github.com/Versent/saml2aws/actions/runs/4390419924/jobs/7688852022
```
• DEPRECATED: --rm-dist was deprecated in favor of --clean, check https://goreleaser.com/deprecations#-rm-dist for more details
```
=> Use --clean with goreleaser

README.md, go.mod, go.sum, pkg/provider/browser/browser.go
#952 
I didn't test browser path of resulting binary
=> Move playwright-go from mxschmitt to playwright-community

pkg/provider/okta/okta.go, pkg/provider/okta/okta_test.go
This PR fixes Okta infinite loop with MFA push, raised in issue #714.
I have tested this on my machine, and have been using it for several months now.
Please note that I'm a complete Go newbie, so any suggestions and improvements are welcome.
=> Fix infinite loop with Okta push

aws_role.go
Some Identity providers add some random stuff to the SAML attribute before/after Principal and Role ARNs. This PR improves the way ARNs are identified and removes this additional stuff.
=> Find tokens by regex

README.md
The ticks are required to prevent that some shells escape the braces
=> Fix wget instructions for linux setup in readme

.github/workflows/go.yml, README.md, cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/creds/creds.go, pkg/flags/flags.go, pkg/provider/browser/browser.go, pkg/provider/browser/browser_test.go
This PR seeks to have the browser IDP option to once again automatically download Browser Drivers as was the default behavior for saml2aws versions <= 2.36.4
This PR would functionally close #1005 
When saml2aws was upgraded to 2.36.5 and using the IDP option of `Browser`, one would get this failure message:
```
Error to authenticating to IdP: could not start driver: fork/exec /Users/alice/Library/Caches/ms-playwright-go/1.20.0-beta-1647057403000/playwright.sh: no such file or directory
```
It appears that as part of upgrading browser binaries and thus playwright as part of issue #952 and PR #982 introduced a version of [playwright-go](https://github.com/playwright-community/playwright-go/releases/tag/v0.2000.0) that had breaking change to the underlying playwright driver that will no …
=> Browser IDP - Configure Browser IDP to automatically install Playwright Browser Drivers per old behavior <= 2.36.4

pkg/provider/pingone/example/selectdevicebutton.html, pkg/provider/pingone/pingone.go, pkg/provider/pingone/pingone_test.go
In the environment I'm working in, the PingOne device names are within a 'button' element rather than an 'a' element. This change checks for device names within a 'button' element if there is no device name found within the 'a' element.
=> Handling PingOne device names within button elements

README.md
The README's installation instructions assume the existence of `~/.local/bin/`. This adds a `mkdir` command to ensure that that directory is present.
=> add mkdir to installation instructions

pkg/provider/okta/okta.go, pkg/provider/okta/okta_test.go
This changes adds the ID of the token to the string in the prompt, which allows users to distinguish tokens with non-unique authNames.
This also fixes the issue where if the authName is the same for all tokens, the first token is always chosen by saml2aws regardless of user selection.
Closes: #910
=> feat: disambiguate Okta U2F tokens using the ID

pkg/provider/okta/okta.go, pkg/provider/okta/okta_test.go
I've been having a weird intermittent issue, where trying to log in would sometimes fail with an opaque message: 
```
Error authenticating to IdP.: failed to getStateToken: error retrieving saml response: cannot find state token
```
After a bunch of digging, I discovered that sometimes Okta will request "extra verification" in the form of another 2fa request. Not a big deal, but for whatever reason that page doesn't store the state token as a single variable. Instead, it's burried deep in a blob of almost-JSON. 
This change lets us dig up state tokens from those pages as well, which mostly fixes the "cannot find state token" message
=> add another regex for finding state tokens

pkg/provider/okta/okta_webauthn.go, pkg/provider/okta/okta_webauthn_test.go
PR #1039 introduced a change to okta_webauthn.go that most probably
is a relic from the development phase of the Duo integration (ref:
82b3ba36c28b94c0138e874177b830b08c1468bb).
Since the Duo integration implements its own ChallengeU2F, this should
be safe to revert.
=> Fix Okta WebAuthn challenge

pkg/prompter/survey.go, pkg/provider/okta/okta_duo_u2f.go
This commit fixes two spots where function comments were mismatched with the code, likely from copy-paste accidents.
Background: I'm doing a research study on function comments that may be improvable. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
 
Thanks for reviewing!
=> Fix small mistakes in function doc comments

pkg/provider/browser/browser.go
`fmt.Println` still logs when `--quiet` is specified and that's problematic when saml2login is being used as credential_process in aws profiles.
=> Use logger instead of fmt.Println in brwoser.go

pkg/provider/browser/browser.go, pkg/provider/browser/browser_test.go
I didn't see an appropriate place to add/update a unit test for this but I have been using it locally and it fixes the issue.  Doesn't seem like an external configuration flag is required but may be if users continue to have issues.
=> Add 5m timeout to page.WaitForRequest

pkg/provider/googleapps/example/challenge-sms-send.html, pkg/provider/googleapps/example/challenge-sms.html, pkg/provider/googleapps/googleapps.go, pkg/provider/googleapps/googleapps_test.go
It seems some times google will present an extra "Send text message" challenge page that requires the user to click on the button to actually get text message sent and present the code input in the next page.
#1137
=> Handle extra "Send text message" challenge page

pkg/provider/browser/browser.go
Solves #1161
The code change that was introduced in https://github.com/Versent/saml2aws/pull/1157/files#diff-5cd59a5a8d31c61bb9c035ee3524699cd8e97b722683501d805074f7d11b7ee9R102-R103
was done because of a signature change with the new release:
https://github.com/playwright-community/playwright-go/blob/main/page.go#L567
The `cb` method is not an error callback, but a general callback which is not mandatory:
https://github.com/playwright-community/playwright-go/blob/ddc7abdd06db016d63664de1ab08870195085ddb/waiter.go#L144
The redirect to blank page created an unwanted side-effect that did not allow saml2aws to continue with AWS role selection as described in #1161.
This is the fix.
FYI @gliptak
=> [Bug fix] remove redirect to about:blank page

README.md
- Remove duplicated Azure AD entry
- Move jumpcloud into idp requirement for consistency
resolves #150
=> docs: move jumpcloud to idp requirements [#150]

README.md
1. `make release` does not exist in the Makefile
2. process has changed since time of writing
=> docs: update releasing instructions

.github/dependabot.yml
Fix dependabot not automatically apply labels to Pull Requests due to `The following labels could not be found: type: dependencies.`
Here is the link to how the labels values should be used https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
=> fix(dependabot): labels could not be found

pkg/provider/browser/browser.go, pkg/provider/browser/browser_test.go, pkg/provider/browser/example/loginpage-button-submit.html, pkg/provider/browser/example/loginpage-without-submit.html
Hello, 
This PR proposition updates the way the autofill func submits the form:
Instead of locating the submit button and clicking on it, it send an Enter keypress.
I had to implement this to make it works with my company authentification web form, which has no html submit button, but an image with javascript events linked to it.
=> Browser provider - Autofill works with more authentication forms

.goreleaser.macos-latest.yml
just like it's done on https://github.com/Versent/saml2aws/blob/master/.goreleaser.ubuntu-20.04.yml#L23-L24
fixes #900 #873
=> fix: enable cgo on macos builds

README.md, pkg/cfg/cfg.go, pkg/provider/keycloak/example/authError-accountDisabled.html, pkg/provider/keycloak/example/authError-accountDisabled_ja.html, pkg/provider/keycloak/example/authError-invalidPassword.html, pkg/provider/keycloak/example/authError-invalidPassword_ja.html, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
This PR is for the issue https://github.com/Versent/saml2aws/issues/1265. Thank you.
=> Customizable KeyCloak password error validator

cmd/saml2aws/commands/login.go, cmd/saml2aws/commands/login_test.go
PR to address this: https://github.com/Versent/saml2aws/issues/895#issuecomment-2117464337
=> Fixing saved credential issue for --credential-process introduced by https://github.com/Versent/saml2aws/pull/896

cmd/saml2aws/main.go
This PR will fix missing providers that exists in the interactive "provider" drop-down but when attempt to pass it in as an argument from the command line, it doesn't matches the hard-coded list which is a sub-set of the providers in the drop-down list.
Current version of saml2aws v2.36.16: (note the enum value, it is missing a few values like PingOne)
```
➜  saml2aws_darwin_arm64 git:(1294-missing-idp-provider) ✗ saml2aws configure --idp-provider=PingOne
saml2aws: error: enum value must be one of Akamai,AzureAD,ADFS,ADFS2,Browser,GoogleApps,Ping,JumpCloud,Okta,OneLogin,PSU,KeyCloak,F5APM,Shibboleth,ShibbolethECP,NetIQ,Auth0, got 'PingOne', try --help
```
The binary built to test the current PR: (note the enum value, PingOne is there)
```
➜  saml2aws_darwin_arm64 …
```
=> Fix missing provider when passing as an argument

README.md, cmd/saml2aws/main.go
A change made between v2.36.15 to v2.36.16 (current version at time of writing) had introduced an unwanted side-effect of not showing MFA phone numbers when using the `--credential-process` flag as it also implicitly applies `--quiet`. 
The line in question that was introduced by a commit that made it into v2.36.16 is https://github.com/Versent/saml2aws/blob/08035b93069c0ca518b13d1ef905e08b95bc1269/cmd/saml2aws/main.go#L172
Looking at the PR https://github.com/Versent/saml2aws/commit/08035b93069c0ca518b13d1ef905e08b95bc1269#diff-700f078cb6e14d20af7c09e73a1507604a85cfb66d6c54db727f45dc21a13d2a, I do not see any potential side-effects in removing the additional conditions in the "quiet" condition statement to "quiet" the logs.
=> fix: credential-process flag remove logs [#1293]

.github/workflows/go.yml, .github/workflows/release.yml
While looking at the GitHub Action runner executing a job, I have noticed an error during the "Set up Go 1.x" stage 
```bash
Warning: Restore cache failed: Dependencies file is not found in /home/runner/work/saml2aws/saml2aws. Supported file pattern: go.sum
```
A quick look at the documentation and it had the `actions/checkout` before the `actions/setup-go`, while we had it afterwards, which probably explains why it cannot find `go.sum`.
Also (the bit that was outside the scope of the initial issue but I wanted to save multiple PRs):
- we are still using Go version 1.20 somewhere and after a quick search, I've came across a way to derive version from go.mod (https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file)
- ran the yaml file against a …
=> fix: gha setup go cache issue [#1319]

.appveyor/appveyor.yml
- Fix "source" flag in the `choco apiKey` command to be in line with the documentation: https://docs.chocolatey.org/en-us/create/commands/api-key/
- Add "source" flag in `choco push` command
- satisfy the response from the failed ci execution: https://ci.appveyor.com/project/davidobrien1985/saml2aws
- using the short-hand `-s` for source to be consistent, I've checked that it does exists in https://docs.chocolatey.org/en-us/create/commands/push/
=> fix(ci): fail to push windows pkg due to missing flag [#1325]

choco/saml2aws.nuspec
Update the authors of the package to Versent, This will also affect the displaying of authors' name in saml2aws Chocolatey package page.
=> chore(nuspec): change authors to Versent

cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/flags/flags.go
When an STS token is acquired, it's possible to use supplemental policies to limit the permissions of the token. One example use might be assuming an administrative role, but limiting the permissions to a read-only or security-review scope to use to provided credentials in an auditing tool. This PR implements assume-time limiting of permissions with additional managed policies or a local policy document.
=> Implement assume-time policy limiting

cmd/saml2aws/commands/login.go, cmd/saml2aws/main.go, pkg/cfg/cfg.go, pkg/creds/creds.go, pkg/flags/flags.go, pkg/provider/keycloak/keycloak.go, pkg/provider/keycloak/keycloak_test.go
This pull request fixes the issues of saml2aws not having the ability to hop multiple request chains to follow keycloak brokers, as well as the issue of it not carrying cookies along with the requests in this chain, which would result in it failing to do any multi-provider hops. 
I mentioned the issue this is solving in #1395 
After looking at how the keycloak authentication chain operates, I've managed to add a flag called "kc-broker" for logging in. This flag you can give a valid kc-broker name, (specified in your keycloak configuration). Keycloak will then take this broker and follow through to the target broker, beginning the authentication chain. Once this process begins the only necessary component that needed adding to saml2aws was for saml2aws to carry cookies forward along the …
=> added kc broker flag

Makefile
- The previous version (1.53.2) was behind the version (1.55.2) used in [GitHub Actions](https://github.com/Versent/saml2aws/blob/148bb41a9d6c1043592ff5d8484813ca545c3138/.github/workflows/go.yml#L52-L56).
- This caused issues with parsing the `toolchain` directive in `go.mod`.
- Additionally, correct the PHONY directive for `make install`.
```sh
$ go version
go version go1.22.5 darwin/arm64
```
```sh
$ make lint
--- lint all the things
level=info msg="[config_reader] Config search paths: [./ /app / /root]"
level=info msg="[config_reader] Used config file .golangci.yaml"
level=info msg="[lintersdb] Active 8 linters: [errcheck goimports gosimple govet ineffassign staticcheck typecheck unused]"
level=info msg="[loader] Go packages loading at mode 575 …
```
=> chore: Upgrade golangci-lint in Makefile to support toolchain directive

cmd/saml2aws/main.go
The link that comes up when using the `--provider` flag is broken.
```sh
$ saml2aws login --provider=Ping
The --provider flag has been replaced with a new configure command. See https://github.com/versent/saml2aws/v2#adding-idp-accounts
```
Corrected https://github.com/versent/saml2aws/v2#adding-idp-accounts link to https://github.com/Versent/saml2aws#configuring-idp-accounts .
The adding-idp-accounts document has been renamed to configuring-idp-accounts with this change.
https://github.com/Versent/saml2aws/commit/7bbdacc9458a61c30e652d0400cc5355f35ca4f7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L71
Also consistent with what we have here.
https://github.com/Versent/saml2aws/blob/64255ff7019612e60de7b5139206f1c514cf4374/README.md?plain=1#L212
=> Fix broken link

pkg/provider/authentik/authentik.go, pkg/provider/authentik/authentik_test.go, pkg/provider/authentik/model.go
Adding support for optional usage of MFA authenticator for IdP Authentik
Without this it is not possible to use authentik provider when MFA like TOTP is configured for a user. Without this added support the only workaround is to use `browser`.
=> Add authenticator support authentik

cmd/saml2aws/commands/configure.go, cmd/saml2aws/commands/console.go
Prior to this change:
- The saml2aws configure command included a password repeater for confirmation, which was unnecessary as this process is not a sign-up flow. If users entered an incorrect password, they could simply re-initiate the configuration process. The password repeater also caused ambiguity when passwords did not match, leading to a poor user experience.
- The console.go file contained a redundant error check for the err variable, which added unnecessary complexity to the code.
After this change:
- The password repeater has been removed entirely from the saml2aws configure command. This simplifies the flow and eliminates the ambiguity caused by the repeater. If users enter an incorrect password, they can now restart the configuration process without confusion.
- The redundant …
=> fix: 🐛 improve password confirmation prompt (fixes #1390)
